# Jvm Info
java_version=21
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=false
org.gradle.debug=false

# Mod Info
mod_id=anvilcraft_chaplus
mod_name=AnvilCraft-ChaPlus
mod_description=An AnvilCraft addon.
mod_author=PaudyanCha
mod_license=LGPL-3.0-or-later
mod_version=0.0.1
mod_url=https://github.com/Paudyancha/AnvilCraft-ChaPlus/

# Development Info
maven_group=dev.anvilcraft.chaplus

minecraft_version_range=[1.21,1.21.1)
neo_version_range=[21.0.0-beta,)
loader_version_range=[4,)

# Publish Info
modrinth_id=
curseforge_id=
